### ISSUE TITLE
Tiles rendering error 

### ISSUE THREAD

**Issue by willianholtz** [mapeditor/tiled#3046] opened 2021-04-29 21:18 UTC
Sometimes when you open the editor, this happens randomly:
![Screenshot_20210429_180610](https://user-images.githubusercontent.com/23488207/116618726-d05b8c00-a915-11eb-8419-1a82f7a1f0d9.png)

I tried to find the reason why it happens, with debug. But it shows nothing.

But, looking at my error logs, the only information you have about such a problem is this:
```
abr 29 18:06:17 archlinux systemd[916]: app-org.mapeditor.Tiled-741f1e08b44347f8b6dd966cd142bc2f.scope: Deactivated successfully.
abr 29 18:06:17 archlinux systemd[916]: app-org.mapeditor.Tiled-741f1e08b44347f8b6dd966cd142bc2f.scope: Consumed 6.405s CPU time.
```
I don't know if it's incompatible with my AMD Radeon HD 6450 graphics card.
I use Arch Linux OS.

**Comment by bjorn** [comment] 2021-04-30 06:57
Right, that seems like some problem in the OpenGL rendering code. I don't think I can fix that in Tiled, but you can avoid it by disabling "Hardware accelerated drawing (OpenGL)" in _Edit > Preferences > Interface_.

**Comment by bjorn** [comment] 2022-02-17 10:46
I'm closing the issue since I can't fix this in Tiled, nor can I report this as a Qt issue without a reliable way to reproduce it.

**Closed by bjorn** 2022-02-17 10:46 UTC
Labels: bug
