### ISSUE TITLE
Change Origin to Bottom Left of Map

### ISSUE THREAD

**Issue by Shr1ftyy** [mapeditor/tiled#3850] opened 2023-12-01 08:04 UTC
It would be great if there is an option for the origin of the map to be at the bottom left of the map rather than at the top left, since it messes with coordinate systems of different graphics libs and engines.

**Comment by bjorn** [comment] 2023-12-01 11:11
This is a duplicate of issue #249. Please see the discussion there as well as the related pull request(s) to understand why this is a tricky thing to support in Tiled.

**Closed by bjorn** 2023-12-01 11:11 UTC
Labels: feature
