### ISSUE TITLE
Downloading tiled on linux using apt-get downloads a version without any plugins

### ISSUE THREAD

**Issue by jplantman** [mapeditor/tiled#2988] opened 2021-02-18 14:54 UTC
Downloading tiled on linux terminal using `sudo apt-get install tiled` downloads a version (version 1.3.2, as of Feb 2021) without any plugins. Which means I can't export a map as JSON. I couldn't find any way to manually download any plugins, so I was left without this important tiled functionality. 

Then downloaded the tiled appImage through the website. That works fine, and comes with a bunch of plugins and lets me export maps as expected. But maybe you guys also want the version downloaded through the terminal to also come with the required plugins, so that it also works fine.

Thanks!

**Comment by bjorn** [comment] 2021-02-18 21:00
Looks like a bit of a duplicate of #2973, see also the discussion at https://github.com/mapeditor/tiled/issues/2973#issuecomment-758901771. Except that report was about version 1.2.1 on Debian Buster and yours about version 1.3.2 on presumably Ubuntu 20.04 or a distribution based on it. The workaround would likely be the same.

Fortunately, this packaging issue seems to be already fixed in newer versions, including the 1.4.2 version shipping in Ubuntu 20.10.

**Closed by bjorn** 2021-02-18 21:00 UTC
