### ISSUE TITLE
Using a tint color with different sprites causes tiles to be black.

### ISSUE THREAD

**Issue by Snowdrama** [mapeditor/tiled#2930] opened 2020-11-05 22:02 UTC
I have a tint color on 3 different layers with 3 different colors but for some reason only one ever shows and the rest of the tiles are black. 

In the following Screenshots I have Blue for Collision, Green for one way collision, and red for hurt collision. What causes the black is the tint itself. Hiding the last layer also reveals the layer above.
![image](https://user-images.githubusercontent.com/1271916/98300669-9bcecf00-1f87-11eb-809f-26659640d3bc.png)
Note the order of the tilemap change
![image](https://user-images.githubusercontent.com/1271916/98300704-a8532780-1f87-11eb-91d1-b9283ffe6cf6.png)
![image](https://user-images.githubusercontent.com/1271916/98300717-ad17db80-1f87-11eb-9cba-e4cab214cee3.png)

Results are also not consistent per layer, Adding a different tile to a single layer also causes the issue, for this example I only have the collision/blue layer revealed. 
![image](https://user-images.githubusercontent.com/1271916/98301076-3cbd8a00-1f88-11eb-91f5-5be134faabe0.png)
Inserting a different sprite into the middle that changes the tint of the new tile placed and every tile after it to black
![image](https://user-images.githubusercontent.com/1271916/98301197-62e32a00-1f88-11eb-9353-c5115a94f67a.png)

Edit: confirmed if you remove the tint this issue goes away.
![image](https://user-images.githubusercontent.com/1271916/98302057-ca4da980-1f89-11eb-8b07-0df980248362.png)

Second Edit:
Windows 10
Tiled Version 1.4.2

**Comment by bjorn** [comment] 2020-11-06 15:29
I'm trying to reproduce this on Linux, latest `master` with the perspective walls example, but for me it appears to be working fine:

![image](https://user-images.githubusercontent.com/531764/98383435-c46ccc80-204c-11eb-9b69-71e148e19921.png)

I'll see if the example shows the problem with Tiled 1.4.2 on Windows 10. I'm not sure if anything actually changed in this regard.

Could you maybe upload a small example archive that reproduces the problem?

**Comment by bjorn** [comment] 2020-11-06 15:31
An example that triggers the problem could really help, cause for me with Tiled 1.4.2 on Windows 10 I don't see the problem with the perspective walls example at least:

![image](https://user-images.githubusercontent.com/531764/98384021-88863700-204d-11eb-9024-ae1c0a0c2701.png)

**Comment by Snowdrama** [comment] 2020-11-06 15:48
Here's a couple maps with issue, as well as videos of me reproducing the issue. 
[TiledBugExample.zip](https://github.com/bjorn/tiled/files/5502112/TiledBugExample.zip)

**Comment by bjorn** [comment] 2020-11-06 19:10
Alright, this only happens when hardware-accelerated rendering (OpenGL) is enabled (and then also on Linux). I'll see if I can fix it, but in the meantime you could switch to software rendering (which usually works better, due to the painting API that is used being rather unsuitable for hardware acceleration).

**Comment by bjorn** [comment] 2020-11-10 11:22
Unfortunately I'm not sure if there is a reasonable solution to this problem. I've labeled this a Qt issue, because I think it should probably be fixed there.

I'm not sure exactly what is causing it, but I suspect it has something to do with the need to convert the QPixmap into an OpenGL texture. The tinted pixmaps are temporary and it seems that whenever the same memory location is re-used, setting up the OpenGL texture fails. I found that one way to fix it would be to keep the pixmaps in memory for each tile + color combination, but this is not acceptable performance-wise. It's unclear when these colored versions can be cleaned up so this would be a significant memory leak.

I think the real way to fix this would be to transition to the new rendering API, so that no temporary tinted images need to be allocated but the tinting can be done in a fragment shader instead.

**Comment by bjorn** [comment] 2022-09-09 09:52
It appears this issue was mostly fixed, probably by caching of tinted pixmaps introduced in 435c6498fc5106a3fc87995e4f37514b727cb640 (Tiled 1.9). I guess it may still happen when the cache is too small for the tinted tiles, but for now I'm closing the issue.

**Closed by bjorn** 2022-09-09 09:52 UTC
Labels: bug, qt issue
