### ISSUE TITLE
Tile highlight remains when scrolling through the map at a specific speed

### ISSUE THREAD

**Issue by NetSysFire** [mapeditor/tiled#3475] opened 2022-09-21 21:53 UTC
**Describe the bug**

~~https://user-images.githubusercontent.com/59517351/191615588-5558c9bc-47ca-4482-b6a2-d78639cf04c3.png~~ - it got better after I updated to 1.9.2 from 1.9.1, but it still happens:

![image](https://user-images.githubusercontent.com/59517351/191616462-324b5710-874a-4ce6-8ff1-689f95ced0a9.png)

*Edit:* I found exactly the right speed for scrolling which makes an even better screenshot: 
![image](https://user-images.githubusercontent.com/59517351/191617548-8ca8f8d6-c56e-4edf-a4ce-35645f42f077.png)

I have no idea what the proper word for that is, so please excuse my potentially inaccurate statements. It looks like the part is not being redrawn correctly.

**To Reproduce**

File used: https://git.themanaworld.org/ml/clientdata/-/blob/master/maps/001-13.tmx

1. Point your cursor anywhere. Preferably in the dark void in the lower part of the map.
2. Scroll at medium speed.
3. The highlight will linger.

**Expected behavior**

Only the highlighted tile should have this blue overlay.

**Specifications:**
 - OS: Arch Linux
 - Tiled Version: 1.9.2-1

**Comment by eishiya** [comment] 2022-09-22 00:01
I think this is a duplicate of #174, a long-standing Qt issue ): As a performance optimization, only the changed region of the map view is redrawn when something changes (such as a highlight, a brush, or edited tiles), but the region to redraw/repaint isn't always calculated correctly - moving the map view is one of the causes.

**Comment by bjorn** [comment] 2022-09-22 07:04
Yes, closing this since it's a duplicate.

Oh how nice it would be to eventually get this issue fixed, but I'm afraid that either I will need to fix it myself in Qt, or we'll fix it by rewriting the map renderer using modern hardware APIs in which case the entire view will be repainted anyway.

**Closed by bjorn** 2022-09-22 07:04 UTC
Labels: bug
