### ISSUE TITLE
[Bug] When I click Flip-H object, it will be Filp-V & rotate 180

### ISSUE THREAD

**Issue by finscn** [mapeditor/tiled#3148] opened 2021-10-04 15:11 UTC
When I use button or key `X` to Flip-H
![image](https://user-images.githubusercontent.com/288367/135876811-8292a237-d804-43a5-8aab-07692e80e3c5.png)

the result is  Filp-V & rotate 180

**Comment by bjorn** [comment] 2021-10-05 07:39
Duplicate of #1704.

**Closed by bjorn** 2021-10-05 07:39 UTC

**Comment by finscn** [comment] 2022-02-15 16:12
@bjorn , this issue is still existing in 1.8.1

**Comment by bjorn** [comment] 2022-02-15 16:16
@finscn I know, but this is still a duplicate issue. Please don't post duplicate comments. :-)
