### ISSUE TITLE
Hotkey for horizontal mirror does something different

### ISSUE THREAD

**Issue by TrunXGIT** [mapeditor/tiled#1817] opened 2017-11-13 21:16 UTC
When you use the hotkey "X" on an object it sets Vertical Mirror to "true" and Rotation to 180.
Effictevly it's the same but still strange and it causes problems with the GMX Exporter.

(The adjustment of the coordinate regarding the origin point is wrong when combining vert mirror with 180° rotation)

**Comment by bjorn** [comment] 2021-10-05 07:40
Duplicate of #1704.

**Closed by bjorn** 2021-10-05 07:40 UTC
Labels: usability

**Comment by bjorn** [comment] 2021-10-05 07:41
Ah, I closed this as duplicate, though probably the coordinate adjustment should still be checked, independently of the confusing "horizontal mirror" behavior. Or was that fixed in the meantime?
