### ISSUE TITLE
Creating a rectangle selection marks the map with unsaved changes

### ISSUE THREAD

**Issue by Macksaur** [mapeditor/tiled#3216] opened 2021-12-18 06:08 UTC
### Problem
When I've got lots of files open and I'm doing a lot of copy/pasting and organizing I have to keep track of what files I have *actually* edited and want to save because tiled spuriously adds the modified flag to open maps on non-destructive operations like selecting and copying.

### Goal
To be able to select and copy tiles from a map without requiring it to be saved again.

**Comment by bjorn** [comment] 2021-12-18 07:00
Duplicate of #3194. But the good news is, I recently implemented this! If you want the change right now you can download an artifact from the Actions tab, making sure to select the master branch and the "Build Packages" workflow.

**Closed by bjorn** 2021-12-18 07:00 UTC

**Comment by Macksaur** [comment] 2021-12-18 07:02
Woops, thank you!
