### ISSUE TITLE
Group layer parallax values not weighted the same as non-groups in Tiled's rendering

### ISSUE THREAD

**Issue by keithnbrown** [mapeditor/tiled#3172] opened 2021-11-05 17:47 UTC
I have a file that makes use of parallax. I had a few layers that used the same parallax values, so i put them in a group and set the parallax value on the group, and reverted the individual layer's parallax values.

The problem is that the result was not the same when viewed in tiled.

The original layers had a parallax value of (1.5, 1)
In order to get the same movement after i put them in a group, the group's parallax value had to be (1.25, 1), which makes no sense to me.

Is this behaviour as designed, and if so, what is the maths going on that makes 1.25 = 1.5 in this situation? If it is a bug, what's causing this difference?

**Comment by NworbLegin** [comment] 2021-11-05 19:27
It looks like this has been fixed already, but not made it into a new release.
https://github.com/mapeditor/tiled/commit/fd36059c9ffc662f909fe1134a728ab44f0b3568

**Comment by NworbLegin** [comment] 2021-11-05 21:36
When is the next release due?

**Comment by bjorn** [comment] 2021-11-08 09:58
> It looks like this has been fixed already, but not made it into a new release.
> [fd36059](https://github.com/mapeditor/tiled/commit/fd36059c9ffc662f909fe1134a728ab44f0b3568)

Right, this is a duplicate of #3124.

> When is the next release due?

I wasn't planning to do another patch release, with the goal of getting Tiled 1.8 out as soon as possible. But while I'm making good progress on that part, it's still going to be a few weeks.

I could re-evaluate the whether it's worth making a 1.7.3 release, though you can also download a build of the latest `master` from https://github.com/mapeditor/tiled/actions/workflows/packages.yml?query=branch%3Amaster (click on latest successful build, scroll to "Artifacts", there's a build for each supported platform).

**Closed by bjorn** 2021-11-08 09:58 UTC

**Comment by NworbLegin** [comment] 2021-11-08 10:18
Thanks for your help
