### ISSUE TITLE
Template instances can't override the flipped states into the gid of the template

### ISSUE THREAD

**Issue by felaugmar** [mapeditor/tiled#1895] opened 2018-02-26 17:50 UTC
When using templates of tile object, the **flipped state**s can only be set in the **template** and cannot be changed in the **object**.

You can **reproduce** it by creating a **template** and trying to modify a **instance's flipped states**.

I`m not sure of a way to solve this, maybe keeping a **gid** attribute with only the **flipped states** in the **object**, but when reading you'll need to pay attention and use the tile from the **template** and not the nonexistent tile **0 (zero)** from the object. **(which is fine for me)**

**Comment by bjorn** [comment] 2018-03-02 09:17
> You can reproduce it by creating a template and trying to modify a instance's flipped states.

This is not the full story, right? I tried to reproduce this but it seemed to work fine. When I tried saving and loading the map though, I noticed the flipped state was not getting saved.

This is probably because an override flag is not getting set. That flag does affect the tile + flipped states though, so when you flip the tile of a template object, it will also override the tile.

> I`m not sure of a way to solve this, maybe keeping a gid attribute with only the flipped states in the object, but when reading you'll need to pay attention and use the tile from the template and not the nonexistent tile 0 (zero) from the object. (which is fine for me)

Unless you really need to override only the flipping bits, I would suggest not making this more complicated than necessary for now. I do agree it's rather unintuitive, so we could consider changing this... the approach you're suggesting doesn't sound bad.

**Comment by bjorn** [comment] 2018-03-02 09:43
Hmm, after fixing the setting of the changed flag, it still didn't work (would write out `gid="0"` to the TMX file). That is because the tileset used by the template is not necessarily part of the map, and as such it has no global ID assigned.

In my case the tileset was part of the map as well though, which probably indicates another bug...

**Comment by bjorn** [comment] 2018-03-02 09:54
> In my case the tileset was part of the map as well though, which probably indicates another bug...

Ok, that is because tilesets that are part of the map do not get added to the tileset manager until after the map is loaded, so once it encounters the same tileset while loading a template it will not find it there and it will load it again. This is getting rather tricky... probably the reference counting of tilesets should be moved from `MapDocument` to the `Map` class.

**Comment by felaugmar** [comment] 2018-03-02 11:55
> This is not the full story, right? I tried to reproduce this but it seemed to work fine. When I tried saving and loading the map though, I noticed the flipped state was not getting saved.

Yes, sorry for not being totally clear here, indeed it does not get saved and loses it states when closing and loading the map again.

> Hmm, after fixing the setting of the changed flag, it still didn't work (would write out gid="0" to the TMX file). That is because the tileset used by the template is not necessarily part of the map, and as such it has no global ID assigned.

It's a bad thing the gid="0"? If keeping only the flipped states in the object's **gid**, the global ID isn't really needed.

**Comment by felaugmar** [comment] 2018-03-02 12:17
> It's a bad thing the gid="0"? If keeping only the flipped states in the object's gid, the global ID isn't really needed.

Oh, I see, it will always override the **flipped states** with false values.

It really is tricky, maybe omitting the **gid** attribute when there's no change in the **flipped states**. And when there's the gid, get it and override the states bits.

**Comment by bjorn** [comment] 2018-03-04 19:25
I've made some changes (see above) that will be included with Tiled 1.1.3 which fix this issue in case the tileset used by the template is also part of the map. Though the whole gid will be overridden in this case, not just the flipping flags.

I think changing the behavior such that you could override only the flipping bits is outside the scope of a patch release, but I'll leave this issue open since we could consider this for Tiled 1.2.

**Closed** 2023-08-02 23:16 UTC
Labels: bug
