### ISSUE TITLE
On tileset click, go to layer

### ISSUE THREAD

**Issue by naknode** [mapeditor/tiled#3256] opened 2022-02-01 00:29 UTC
Let's say you have a orthogonal 2D tile map. Two layers, background and foreground with two tilesets. One for each layer that will always stay in their respective layer.

Is there a way on Tiled to make it so when you click on, for example, the background tileset, for Tiled to automatically go to the "Background" layer? One less click. Less work.

**Comment by eishiya** [comment] 2022-02-01 01:27
This is not currently possible, since Tiled has no concept of associating tilesets with layers. It's also not currently possible with scripting, because scripting has no way to react to the selected tile/tileset changing, except as part of a scripted Tool.

If a signal like `MapEditor.selectedTilesChanged` is added, it would be possible to write a script that checks the currently selected tiles' tileset and changes the selected layer(s) in the current map.

**Comment by bjorn** [comment] 2022-02-01 05:39
> If a signal like `MapEditor.selectedTilesChanged` (akin to the `MapEditor.currentWangColorIndexChanged` signal that was recently added) is added, it would be possible to write a script that checks the currently selected tiles' tileset and changes the selected layer(s) in the current map when it sees that signal.

I had a quick look, and actually there are undocumented `currentTileChanged` and `stampCaptured` signals on the [TilesetsView](https://www.mapeditor.org/docs/scripting/interfaces/tilesetsview.html#selectedtiles). So you could use for example:
```js
tiled.mapEditor.tilesetsView.currentTileChanged.connect(() => {
    tiled.log(tiled.mapEditor.tilesetsView.selectedTiles);
});
```

The feature might still make sense as a built-in, but it should be possible to select a layer by name based on a custom tile or tileset property.

**Comment by eishiya** [comment] 2022-02-01 12:53
Just how many undocumented signals are out there? I even checked TilesetsView hoping there was a signal like that. 🤣 My \#1 request for Tiled: document the signals available xP ~~Ideally on a single page so they're easier to find.~~

**Comment by bjorn** [comment] 2022-02-01 13:28
> document the signals available

Right, so I've actually tried to do this in adding the missing "changed" signals in 0c7b83d34b7c2ce873128b15c63cdfdcb8c34372, but this one is kind of an "accidental signal", that wasn't intentionally exposed to the scripts. It just happens to be part of the `TilesetDock` class that I decided to expose directly (for better or worse, since this actually allows you to change its window title, floating status, etc...).

**Comment by naknode** [comment] 2022-02-03 05:20
@bjorn Thank you. Promising. Is this where I can get started on scripting? https://doc.mapeditor.org/en/stable/reference/scripting/

**Comment by bjorn** [comment] 2022-02-03 07:37
> From a cursory glance, I injected what you wrote and it _seems_ like it would do trick ... but alas.. nothing?

Well, what I wrote was just a start, and it just logs to the Console some debug print of which tiles are selected each time the current tile changes. To be actually useful, you'd have to:

* Set a custom property on your tiles, probably a string property called "layer", and give it the name of the layer. Note that you can assign a property to multiple tiles at once.
* In the script, get the first tile from the `selectedTiles` and get its layer property, for example `let layerName = selectedTiles[0].property("layer")`.
* Iterate over all layers of the map, looking for one with the given name. That's less trivial than it sounds, but [here's an example doing the same with the layer ID](https://github.com/mapeditor/tiled-extensions/blob/b9edee236112d23676aae37c78878e412847f0c6/find-layer-by-id.js#L11-L27), which could be adjusted.
* Set that layer to be the current one, with `tiled.activeAsset.currentLayer = foundLayer`.

**Comment by naknode** [comment] 2022-02-04 03:26
```javascript
tiled.mapEditor.tilesetsView.currentTileChanged.connect(() => {
  tiled.log(tiled.mapEditor.tilesetsView.selectedTiles);
  tiled.log(tiled.mapEditor.tilesetsView.selectedTiles.length);
  let layerName = tiled.mapEditor.tilesetsView.selectedTiles[0].property("layer");
  tiled.log(layerName);
  tiled.log("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
});
```

output:

```
Tiled::EditableTile(0x55d6e651c400)
1

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
```

![image](https://user-images.githubusercontent.com/616320/152467032-1ec2c278-54fc-4f99-99e9-9104d467724e.png)


How can get the layer name if this custom property I am trying to fetch won't be returned? What am I doing wrong?

**Comment by eishiya** [comment] 2022-02-04 03:33
`tiled.mapEditor.tilesetsView.selectedTiles` is not a layer, it's the array of tiles currently selected in the tilesets panel. Object.keys returns the keys of the values of that array, which are just the object indices. If you're getting a 0, it's probably because the array contains just one index: index 0, containing the first selected tiles.

`tiled.mapEditor.tilesetsView.selectedTiles[0].property("layer");` returns the value of the "layer" property of the currently selected tile correctly for me.

**Comment by naknode** [comment] 2022-02-04 03:46
AH. Ah. I see. You're getting the _tile_. I need to learn to read. I was doing the layers (tileset) property and getting nothing. I amended the tileset and did the same.. I see. I see.

I can just do `tiled.activeAsset.currentLayer` by looking at the `type` property on the tile and setting it there.

**Comment by eishiya** [comment] 2022-02-04 03:52
Yep! Just make sure you check that the activeAsset.isTileMap before you try to do anything with its layers.

Also, watch out for that issue I mentioned where the `tiled.mapEditor.tilesetsView.currentTileChanged` signal seems to trigger before `tiled.mapEditor.tilesetsView.selectedTiles` is updated, causing the script to be "behind" a tile. @bjorn Is this intentional? Am I running into a bug/regression when I test that script?

```js
tiled.mapEditor.tilesetsView.currentTileChanged.connect(() => {
	tiled.log( tiled.mapEditor.tilesetsView.selectedTiles[0].id );
});
```
consistently shows me the ID of the tile I *previously* clicked rather than the tile I *just* clicked...

**Comment by naknode** [comment] 2022-02-04 03:58
Yeah. I'm getting it now. I see. And yeah, that's interesting. 

Look at the API, https://www.mapeditor.org/docs/scripting/classes/layer.html looks like I have to get the layer and select it, too. Hmm more work to do it seems for me.

**Comment by eishiya** [comment] 2022-02-04 04:08
Yes, you'll need to iterate all the layers until you find the one you want. If you use groups, this can get complicated. Here's a recursive function that'll take care of that, plus some extra code you may find useful.

```js
let map = tiled.activeAsset;
if(!map.isTileMap)
	return;

let targetName = /* read the name from the selected tile property, as you figured out in earlier posts */;

function findLayer(curLayer) {
	if(curLayer.isGroupLayer || curLayer.isTileMap) {
		let numLayers = curLayer.layerCount;
		for(let layerID = 0; layerID < numLayers; layerID++) {
			let found = findLayer(curLayer.layerAt(layerID));
			if(found)
				return found;
		}
	} else if(curLayer.name == targetName)
		return curLayer;
	
	return null;
}

let layer = findLayer(map);
if(layer) //only change the layer if a match was found
	map.currentLayer = layer;
```

**Comment by naknode** [comment] 2022-02-04 04:26
Yeah. I was looking for `tiled.activeAsset`. Thank you. I got what I needed and this issue has opened a whole new world for me. Thank you!

You may close this issue if need be.

**Comment by bjorn** [comment] 2022-02-04 07:55
> Also, watch out for that issue I mentioned where the `tiled.mapEditor.tilesetsView.currentTileChanged` signal seems to trigger before `tiled.mapEditor.tilesetsView.selectedTiles` is updated, causing the script to be "behind" a tile.

Right, something I hadn't realized (and this was an accidentally exposed signal, remember?). Maybe it works better if you connect to the other accidental signal, `stampCaptured`, instead.

> You may close this issue if need be.

Alright, I'll closed this issue.

The synchronization could also be implemented in the other direction, so that when you change the layer (`TileMap.selectedLayersChanged`) you would set `tiled.mapEditor.tilesetsView.currentTileset` to the one matching the selected layer's name.

Btw, since this kind of functionality seems useful to other people as well, you should consider publishing your extension. :-)

**Closed by bjorn** 2022-02-04 07:55 UTC
