### ISSUE TITLE
Doubled parallax factor for group contents

### ISSUE THREAD

**Issue by nklbdev** [mapeditor/tiled#3157] opened 2021-10-08 00:13 UTC
When I create a group of layers, put several layers in it, and specify the parallax factor for group, then parallax will be displayed in doubled manner.
For example, the following two cases will look the same:

```
// first case
Tile Layer with parallax factor (0.8, 0.8)

// second case
Group with parallax factor (0.9, 0.9)
    Tile Layer with parallax factor (1, 1)
```

It looks like parallax layer for TileLayer in Group equals:

```
right_parallax_factor = Vector2.ONE - (Vector2.ONE - tile_layer.parallax_factor) * 2
```

**Comment by bjorn** [comment] 2021-10-08 06:22
This is a duplicate of issue #3124, which has been fixed but the fix has not been released yet.

Automated builds with the fix included are available at https://github.com/mapeditor/tiled/actions/workflows/packages.yml?query=branch%3Amaster if you need the fix right now.

Thanks for the report!

**Closed by bjorn** 2021-10-08 06:22 UTC
