### ISSUE TITLE
Property Type: "List"

### ISSUE THREAD

**Issue by TheMaverickProgrammer** [mapeditor/tiled#3360] opened 2022-05-18 03:16 UTC
**Is your feature request related to a problem? Please describe.**
We used Tiled for our game and we need to supply a list of values. Usually it's a list of strings for things like conversations but with the addition of Custom Types in Tiled 1.8, we were hoping to supply a list of custom property values to describe our shop keep's inventory. We are surprised there is no way to define a list what-so-ever.

**Describe the solution you'd like**
A list is just a container of elements of any type. The xml should be simple in that regard. 
We should be able to do something like:
Create Property -> Click List -> List Of? -> Click Strings -> Click + new element -> type string "example" -> save file

**Describe alternatives you've considered**
There's no way to do this at all.

**Comment by EJlol** [comment] 2022-05-18 06:32
This is a duplicate of https://github.com/mapeditor/tiled/issues/1493.

**Comment by TheMaverickProgrammer** [comment] 2022-05-18 06:36
> 2017

oof. not looking good there champ

**Comment by bjorn** [comment] 2022-05-18 06:59
> oof. not looking good there champ

Fortunately the age of a request does not necessarily have anything to do with time until it might get done. For Tiled 1.8 I've done a lot of work on the custom property system, adding support for custom classes and enums. Adding support for arrays would be one of the next things to do. My focus for Tiled 1.9 is on the AutoMapping feature, though.

Please feel free to add your thoughts to #1493 in the meantime. Even better if you can help realize this feature. :-)

**Closed by bjorn** 2022-05-18 06:59 UTC
Labels: feature

**Comment by TheMaverickProgrammer** [comment] 2022-05-18 07:10
> Even better if you can help realize this feature. :-)

ok I can take payments in crypto
