### ISSUE TITLE
No sprite image inside Collision Editor window

### ISSUE THREAD

**Issue by odragora** [mapeditor/tiled#1810] opened 2017-11-02 13:44 UTC
#### Steps to reproduce
Create a Tileset
Select a tile
Click "Open Tile Collision Editor"

#### Expected result
Sprite image is shown in the editor with a possibility to add collision shapes

#### Actual result
Collision Editor window is gray, the only thing that is visible besides the buttons is a rectangle shape on ~10000% zoom

#### Tiled versions
1.0.3 32bit 
Latest snapshot 32bit

#### OS
Windows 10 64bit

##### Zoom 100%, image 164x144, isometric tileset
![Zoom 100%, image 164x144](https://image.prntscr.com/image/qPaoSor2RHeDPKuIPAf3xA.png)

##### Zoom 18000%, image 164x144, isometric tileset
![Zoom 18000%, image 164x144](https://image.prntscr.com/image/2VbvJSNAS4i-pLtGls53_g.png)

**Comment by bjorn** [comment] 2018-02-12 19:22
Seems I forgot to get back to this issue. Can you still reproduce this in the latest version (Tiled 1.1.2 or a development snapshot)? I've never encountered this issue despite having done several changes related to the tile collision editor.

If you can still reproduce it, please attach the files (preferable both the `tsx` file and the images it refers to, as a zip file). As long as I can easily reproduce the problem it should generally not be hard to fix.

**Comment by bjorn** [comment] 2021-09-16 11:52
Seems that #2892 was opened as a duplicate of this, and it was fixed in 6812802a0762117f357c7d1aa0153fea490faa62.

**Closed by bjorn** 2021-09-16 11:52 UTC
