### ISSUE TITLE
Scripting: Array values sometimes `null` when saved locally

### ISSUE THREAD

**Issue by eishiya** [mapeditor/tiled#3565] opened 2023-02-05 23:03 UTC
Sometimes, values in Tiled that should not be null, such as layers from `TileMap.layers`, objects from `ObjectGroup.objects`, and tiles from `Tileset.tiles` are `null` when they shouldn't be, but apparently only when a local copy of the array or value is saved.

Since accessing these arrays re-creates the array anew every time, it's usually recommended to save local copies to improve performance, but doing so sometimes produces this bug.

Here is an example action that demonstrates the unexpected behaviour. For convenience, I've also provided an action that calls this action 10000 times, as the vast majority of runs will work just fine.
```javascript
var randomNull = tiled.registerAction("RandomNullTest", function(action) {
	let map = tiled.activeAsset;
	if(!map || !map.isTileMap) return;
	let layers = map.layers;
	for(let l = 0; l < map.layerCount; l++) {
		let layer = layers[l];
		if(layer == null) { //Compare with: if(map.layers[l] == null) {
			tiled.log("Unexpected null layer! "+l);
		}
	}
});

var randomNullMulti = tiled.registerAction("RandomNullMultiTest", function(action) {
	for(let i = 0; i < 10000; i++) {
		tiled.trigger("RandomNullTest");
	}
});
```
To see the behaviour in action:
1. Run the script above through the Tiled console or your extensions directory
2. Open or create a map with a few layers.
3. Run the "RandomNullMultiTest" action, e.g. with `tiled.trigger("RandomNullMultiTest");` in the console. The bug occurs randomly, so you may need to run the action more than once.

Expected output: Nothing. No layers should be `null` in `layers`.
Actual output (this example was from a map with 3 layers):
```md
> tiled.trigger("RandomNullMultiTest");
Unexpected null layer! 0
Unexpected null layer! 1
Unexpected null layer! 2
Unexpected null layer! 0
Unexpected null layer! 1
Unexpected null layer! 2
Unexpected null layer! 0
Unexpected null layer! 1
Unexpected null layer! 2
Unexpected null layer! 0
Unexpected null layer! 1
Unexpected null layer! 2
Unexpected null layer! 0
Unexpected null layer! 1
Unexpected null layer! 2
```
**However**, if instead of using the local `layer` or `layers` variables, I check `map.layers[l]` directly, this issue doesn't seem to ever occur. Saving *either* locally (e.g. `layer = map.layers[l]; if(layer == null`, or `if(layers[l] == null)`) still causes the issue.

Another user (Bongo on Discord) ran into a similar issue with objects, in a function structured like this:
```javascript
function exportObjects(objectLayer) {
	for (let c = 0; c < objectLayer.objectCount; c++) {
		let object = objectLayer.objects[c];
		//object is sometimes null!
		//using objectLayer.objects[c] instead of object always works
	}
}
```
It seems like when saving JS-side references to C++ objects, the references sometimes become broken and the JS variable becomes `null`.

OS: Windows 10 x64
Tiled version: 1.9.1 and 1.9.2 today, but I've run into this issue on older versions as well, pretty much as long as I've been writing Tiled scripts

**Comment by bjorn** [comment] 2023-02-06 12:28
While I could reproduce this issue with a build against Qt 5.15.2, I could no longer reproduce it when compiling Tiled against Qt 6.4.2. I hence suspect this to be a Qt issue (related to garbage collection, most likely) which has been fixed in the meantime.

I'll look into making Tiled 1.10 builds against Qt 6, cause I think all Qt 6 related issues have now been fixed.

**Comment by bjorn** [comment] 2023-02-15 10:56
Closing this since the releases have now been updated to Qt 6.4.2. Please reopen when it can still be reproduced in a Qt 6 build.

**Comment by eishiya** [comment] 2023-10-11 23:47
Getting this issue in Tiled 1.10.2 (Qt 6.4.3), the script from the OP produces "unexpected null layer"s.

Someone using one of my scripts reported this, for some reason `map.selectedLayers[validIndex]` would sometimes be `null`. This prompted us to try the minimum script above and we both encountered the problem.

**Closed** 2023-11-16 13:16 UTC
Labels: bug, qt issue
