### ISSUE TITLE
Can't get AutoMap to work.

### ISSUE THREAD

**Issue by jramstedt** [mapeditor/tiled#2179] opened 2019-08-12 00:00 UTC
Running AutoMap doesn't do anything. It doesn't even create missing layers.
I attached a simple test.

I'm running version 1.2.4 on Windows (64-bit).

[mappertest.zip](https://github.com/bjorn/tiled/files/3490572/mappertest.zip)

**Comment by jramstedt** [comment] 2019-08-14 20:57
Same problem with the latest snapshot.

**Comment by bjorn** [comment] 2019-08-15 11:25
@jramstedt Thanks for verifying whether it may be due to a problem that was fixed in the meantime.

I haven't had time to look into your issue yet. Please consider asking on the forums or on Discord because there are some who use automapping quite a bit who may be able to help you as well.

**Comment by bjorn** [comment] 2019-08-18 14:57
@jramstedt The problem is that you've specified a single "regions" layer, while for this rule to work as might be intended it needs a separate "regions_input" and "regions_output" layer. This is because there are empty tiles in the input layer, which, when there are no "inputnot" layers, mean that the rule will not match against any tiles that are either tile 0 or the empty tile (because those tiles are used in the input region).

Another way to work around this problem is to use an "inputnot" layer to specify which tiles you do not want to have in the rest of the input region. This will override the default behavior, meaning empty tiles are then allowed.

Finally, if you really want to require those other tiles to be empty, you can use the [`StrictEmpty` property](https://doc.mapeditor.org/en/latest/manual/automapping/#layer-properties) on the input layer.

The behavior with the empty tiles really needs to be properly documented...

**Comment by lukKowalski** [comment] 2021-12-10 07:28
>The behavior with the empty tiles really needs to be properly documented...

I've landed here because i was having the same problem and actually created a repo, put my tmx there and came here to create an issue, but i've realised maybe it's good idea to first search for already existing ones, maybe there is sth similar to mine... and here i am. So basically i guess it all comes from the many tutorials on YT which proves quite opposite to what you are saying, maybe because they are based on older versions which back then worked a bit different? Here is one of examples: https://youtu.be/aQd3pDHhm3c?t=361

It shows the moment where author creates a region, in the input layer he uses just the part of the region and in the output he uses another part of it and it simply works (didn't work for me though, that's why i'm here) 

From what you are saying he should fill entire region in the input layer to make it work, at least that's what i understood from your last posts in this thread.

This is the repo i've made: https://github.com/lukKowalski/tiled-automap-bug (simply doing the same as the author of that video, but it doesn't output anything for me)

I'm guessing many people are having this problem with automap feature and eventually end up here or on the forum or simply give up. For me it took 2-3h to get here and actually understand the issue with empty input/region tiles so it would be nice to make it more obvious in the docs somehow.

Thank you for making such a great tool btw! ❤️

**Comment by bjorn** [comment] 2021-12-10 10:28
> From what you are saying he should fill entire region in the input layer to make it work, at least that's what i understood from your last posts in this thread.

It's a very old video indeed, but I don't think this behavior has changed since then. The reason why it works in the video, is indeed because the rest of the map is entirely filled with another tile, and this is exactly what the empty tiles within the input region match on (it matches any non-empty tile that also isn't one of the tiles that are part of the input of a rule).

In the map with which you reproduced the issue, the input layer contains empty tiles, which prevent the rule from matching.

> I'm guessing many people are having this problem with automap feature and eventually end up here or on the forum or simply give up. For me it took 2-3h to get here and actually understand the issue with empty input/region tiles so it would be nice to make it more obvious in the docs somehow.

Yeah, I'm sorry for the amount of time that cost you. Many people also come to the Discord, where it's often faster to get an answer. In addition to making this more clear in the docs, there are also plans to make AutoMapping more intuitive, for example as described in issue #3100.

> Thank you for making such a great tool btw!

You're welcome! I recently started working full time on this tool, so hopefully we can close such issues faster now! :-)

**Comment by lukKowalski** [comment] 2021-12-10 10:31
> The reason why it works in the video, is indeed because the rest of the map is entirely filled with another tile, and this is exactly what the empty tiles within the input region match on

Ahh, it makes so much sense now, i've seen few videos and it was working on each of them, each of them also had the map filled with other tiles :)

**Closed** 2021-12-15 16:53 UTC
Labels: documentation, help wanted

**Comment by bjorn** [comment] 2021-12-15 17:07
@jramstedt @lukKowalski I've extended the documentation regarding this behavior, please see the note added to this section: https://doc.mapeditor.org/en/latest/manual/automapping.html#definition-of-inputs. I hope it helps you and future people running into this!

**Comment by lukKowalski** [comment] 2021-12-15 18:01
It's a lot better, thx for adding this!
