### ISSUE TITLE
Custom Classes Member properties do not export to Lua file

### ISSUE THREAD

**Issue by ghost** [mapeditor/tiled#3315] opened 2022-03-27 01:16 UTC
### Issue 1
The new RepeatX and RepeatY properties for image layers do not export to Lua files. The value is always set to "false" even when they are set to true in Tiled.

**Steps**
1. Create a new map.
2. Add an Image Layer to the map layers.
3. Check either of the Repeat X or Repeat Y check boxes in the image layer properties list.
4. Save and export the map as a Lua file.

### Issue 2
The members for new Custom Class properties do not export to Lua files. The property value is exported as an empty Lua table.

**Steps**
1. Select View > Property Types Editor.
2. Click "Add Class".
3. Click "Add Member", give the member a name and a default value.
4. For any layer or map, click the + for Custom Properties.
5. Add a new property type for the new class.
6. Save and export the map as a Lua file.

### Example

![export_defect](https://user-images.githubusercontent.com/6952048/160262493-f804f01e-610c-4ff1-9f9f-6f03fda62647.png)

When exported to a Lua file, these properties will look as follows:
```
          ...
          repeatx = false,
          repeaty = false,
          properties = {
                ["myprop"] = {}
          }
```

**Comment by eishiya** [comment] 2022-03-27 01:21
This is probably a duplicate of #3307, as the underlying problem was that Tiled wasn't copying these properties into the copy of the map that gets passed to the various exporters. It'll be fixed in 1.8.3.

**Comment by dennisfortin** [comment] 2022-03-27 01:29
Ah, shoot. I was trying not to open a duplicate, but I forgot the is:open filter was on. I'll wait for 1.8.3.

**Comment by eishiya** [comment] 2022-03-27 01:33
I also had a look at Issue 2 in one of the nightly builds, and that looks fixed too:
![image](https://user-images.githubusercontent.com/70545646/160262874-dc96f10f-297a-4108-b4e6-4fcca0eff2fa.png)
```lua
  properties = {
    ["myprop"] = {
      ["int prop"] = 3
    }
  },
```

**Comment by bjorn** [comment] 2022-03-28 07:43
> Issue 1 is a duplicate of #3307

That is correct.

> I also had a look at Issue 2 in one of the nightly builds, and that looks fixed too:

No, actually the issue is here, that @dennisfortin didn't set any of the members of that class, and the default values are not written out.

For those that actually need the full classes written out, the plan was to make an export option for this, or to make it part of the "Resolve types and properties" export option. If there's nothing against the latter I can look into doing that as part of Tiled 1.8.3.

**Comment by eishiya** [comment] 2022-03-28 12:40
> No, actually the issue is here, that @dennisfortin didn't set any of the members of that class, and the default values are not written out.

Ah, good catch. In the screenshot, since the properties were black, I thought they were manually set. Do classes members not have a visual distinction between set and unset/default values?

**Comment by bjorn** [comment] 2022-03-28 12:49
> Do classes members not have a visual distinction between set and unset/default values?

They do, but it's not graying out, instead the set members have their name displayed in bold.

**Comment by eishiya** [comment] 2022-03-28 15:10
> They do, but it's not graying out, instead the set members have their name displayed in bold.

Ah. I think that's too subtle, I didn't notice it ): Is there a reason it's done differently for class members? It's not possible for a class member to be unset in both ways at once or to be set in one way but not in another, so I don't think the two different visualisations are necessary.

**Comment by Immow** [comment] 2024-02-25 14:24
Hello, seems that in the latest version of Tiled (1.10.2) the above issue is still there.
When you export your map to a lua file it does not export Class properties.

**Comment by eishiya** [comment] 2024-02-25 14:28
Are you using the "resolve object types and properties" export setting?

If your class is used as a custom property type, rather than as a class directly on some entity (Object, Tile, Layer, etc), those properties are currently not resolved even if that export setting is used, and this applies to *all* export types, not just Lua (see #3411).

**Comment by Immow** [comment] 2024-02-25 15:03
![image](https://github.com/mapeditor/tiled/assets/37532647/5b1aa113-ecaf-49bf-86bb-b7bb58d0f54b)
This property gets exported just fine in Tiled 1.9.2
I turned on:
![image](https://github.com/mapeditor/tiled/assets/37532647/eacd3e79-a256-4087-8519-bd97e5e01508)
And the issue still persists.

**Comment by eishiya** [comment] 2024-02-25 15:03
As I added to my previous comment, this issue has not yet been resolved, that's why it's still open. It's on the roadmap.

**Closed** 2024-03-12 09:17 UTC
Labels: missing feature
