### ISSUE TITLE
Automatic layer customization

### ISSUE THREAD

**Issue by willianholtz** [mapeditor/tiled#3469] opened 2022-09-07 14:00 UTC
I use Tiled a lot and I had an idea that **I don't know if it would be easy to implement** but that could be of good use for more advanced users (or even novices).

**Automatic layers:**

When we are customizing our tiles, we have several properties that we can modify, the idea here would be to add a field called "Layer" in which this field would have a name that the user would put, just like in the image:

![Tiled](https://user-images.githubusercontent.com/23488207/188895006-3ccfe20c-2542-4c75-9a66-be35d3d78b8e.png)

After this customization, and logically save the project, when we insert the region that we customized, this region would automatically be inserted in the layer in question. If the layer does not exist, it creates it. To define whether the layer would be above or below others, would we have to identify it with a number, maybe an ID?

Now if this option is not used, it remains the same as it currently is, the object's position would be on the highlighted layer.

**Simplifying the idea:**

Each custom Tile creates a layer (if it doesn't exist) to make map creation more dynamic and easier.

**Comment by bjorn** [comment] 2022-09-07 18:52
I close this as a duplicate of #1531 (and related to #1351). It's still a good idea to revive this topic since I agree it would be a very useful feature. Please feel free to comment on those issues with any additional insights.

Btw, I think Tiled is looking great on your Plasma desktop! :-)

**Closed by bjorn** 2022-09-07 18:52 UTC
Labels: feature
