### ISSUE TITLE
Custom type default values not exported

### ISSUE THREAD

**Issue by DanielPower** [mapeditor/tiled#3581] opened 2023-02-19 04:39 UTC
**Describe the bug**

When using custom types, if a value is not modified, it will not be included in exports.
If you modify the value, then set it back to the default, it will be included in the export.

**To Reproduce**
1. Create a custom type
  a. View -> Custom Types Editor
  b. Add Class
  c. Add Member
  d. Select 'float' as the type
  e. set 3.0 as the default value
  f. close the custom type editor
2. Select an object
3. Add a property to the object, selecting the newly created custom type
  a. Do not modify the value, it should default to 3.0
4. Export the map as lua

Note that when inspecting the lua file, the custom property will have an empty table as its value.

5. Change the value of the custom property to antother value, then back to 3.0
6. Export the map as lua

Note that when inspecting the lua file, the custom property will appropriately have a field with the value 3.0

**Expected behavior**
Default values should be included in the export.

**Specifications:**
 - OS: Archlinux
 - Tiled Version: 1.9.2

**Comment by eishiya** [comment] 2023-02-19 14:18
Duplicate of #3411

**Comment by DanielPower** [comment] 2023-02-19 21:30
That checks out. I'll close this issue in favor of #3411

**Closed** 2023-02-19 21:31 UTC
Labels: bug
