### ISSUE TITLE
Tiled Fusion theme uses wrong colours

### ISSUE THREAD

**Issue by eishiya** [mapeditor/tiled#3333] opened 2022-04-10 14:59 UTC
Tiled seems to be using the Native theme colours instead of Tiled Fusion theme colours for
- Selected items in panels, when the panel or Tiled is not in focus
- Checkboxes in the Object Types Editor (and possibly the Property Types Editor?), when the checkbox field is not the active one.

This screenshot shows both:
![image](https://user-images.githubusercontent.com/70545646/162625435-19c76cb2-ea95-4443-90de-5f1a88092295.png)
Checkboxes elsewhere seem fine, but it looks like selected properties are affected in all panels:
![image](https://user-images.githubusercontent.com/70545646/162625297-207e05ea-66f1-454a-a007-16611c5be64a.png)

**Reproduce**
1. Switch to Tiled Fusion theme, and set a dark colour if your Native theme is light, or a light colour if your Native theme is dark, so that it's easier to see when the colours are incorrect.
2. Open or create a map, and select a layer.
3. Click off the Layers panel. The selected layer's name will become black instead of keeping its colour.
4. Open the Object Types Editor, and select or create a type with a boolean property, so it displays a checkbox.
5. Click anywhere but the checkbox field. The checkboxes will not match the theme colour. If you click the checkbox field, it will look correct.

**Expected behaviour**
On dark themes, when the panel is active, selected text is white. I expect it to remain white when the panel is not in focus, as it did on older (Qt5?) versions of Tiled. The colour changing to black is distracting, and makes the text harder to read. Similarly, I expect checkboxes to always match the theme colour, regardless of whether the field they're in is selected.

**Specifications:**
 - OS: Windows 10
 - Tiled Version: 1.8.9 (1.9 alpha) 64-bit, and I experienced this issue on the nightlies. I suspect it may be connected to Qt6, as I don't think the Qt5 builds had this problem.

**Comment by bjorn** [comment] 2022-04-25 12:08
It's a change in Qt that seems like a bug to me, where the highlighted text appears to not get set on the widget correctly. It hence also affects Qt's own Fusion style. I can do a workaround, but I should also try reproducing it with a small example for a bug report.

**Comment by bjorn** [comment] 2022-05-16 09:01
> * Checkboxes in the Object Types Editor (and possibly the Property Types Editor?), when the checkbox field is not the active one.

This is a separate bug, which also occurs on Qt 5 since it's due to the checkbox being drawn as an icon that is only drawn once, so it does not respond to theme changes:

https://github.com/mapeditor/tiled/blob/42ce14a7aac427b0cab4be8d601fe237895d0517/src/qtpropertybrowser/src/qtpropertymanager.cpp#L1626-L1630

I guess that could be fixed by introducing some method to repaint those icons after theme changes.

**Closed** 2022-06-24 15:19 UTC
Labels: bug, qt issue
