### ISSUE TITLE
reorder tilesets used in maps

### ISSUE THREAD

**Issue by sverx** [mapeditor/tiled#3090] opened 2021-06-29 12:22 UTC
As discussed on Discord a few days ago, it would be really handy to be able to reorder tilesets used in a map.
The reorder could be triggered by dragging a tileset tab over the tileset tab list, for instance.
The list of tileset should reflect the new order in the list and even in the saved file, which means the tile GIDs will change in the file data (no change of the local IDs).

**Comment by bjorn** [comment] 2021-06-29 12:28
This is a duplicate of issue #1613. I see I've "added" that issue to the roadmap, with some plan to handle it, though that plan is not really what is suggested here. If needed please add to the discussion there.

**Closed by bjorn** 2021-06-29 12:28 UTC

**Comment by sverx** [comment] 2021-06-29 13:33
Sorry, I couldn't find that even if I actually searched if that issue was already open. My fault for using 'reorder' in my search instead of 're-arrange' :facepalm:
