### ISSUE TITLE
Keyboard Shortcuts not working in Ubuntu 16.04

### ISSUE THREAD

**Issue by ketanhwr** [mapeditor/tiled#1458] opened 2017-03-01 12:57 UTC
I'm using Tiled latest developer build (from current `master` branch) and I've noticed that only a few keyboard shortcuts are working for me. I'm using Ubuntu 16.04.

The keyboard shortcuts for `Stamp Brush`, `Terrain Brush`, `Bucket Fill Tool`, etc are working, but `Ctrl+Z` for `Undo`, `Zoom in` and `Zoom out` (`Ctrl++` `Ctrl+-`) aren't working. I've not tried every keyboard shortcut, but `Ctrl+E` for Export isn't working too.

Can anyone reproduce this?

**Comment by bjorn** [comment] 2017-03-02 22:01
They're working fine on Arch Linux / Xfce. I could try later on Xubuntu 16.10, but I fear it may be related to the customized menus in standard Ubuntu / Unity and I don't have an install ready for testing.

**Comment by vadi2** [comment] 2017-03-18 07:46
It's most likely due to @ketanhwr using Qt 5.7 or 5.8 and runnning Ubuntu - I believe the bug is localised to that combination.

**Comment by bjorn** [comment] 2017-03-18 07:54
@vadi2 Provided a link to [QTBUG-59557](https://bugreports.qt.io/browse/QTBUG-59557) in #1497, which covers this issue.

**Comment by bjorn** [comment] 2021-08-10 08:16
The Qt issue was closed as "cannot reproduce" against Qt 5.10. Since it's been over 4 years now and no additional reports of this kind have come in, I'll close this issue as well.

**Closed by bjorn** 2021-08-10 08:16 UTC
Labels: bug, qt issue
