### ISSUE TITLE
Tiled doesn't remember widget size

### ISSUE THREAD

**Issue by Gornova** [mapeditor/tiled#590] opened 2014-01-12 20:46 UTC
My test case: create a new map with tiled, then resize tileset preview to bigger than levels (for example) then close.
On next tiled running, my adjustment on tiled widget size are gone, so I need to do it again and again.
Could you add a preference to save widget height (and not just position?)

Here my 2 screens to show my problem:

1) widget with custom height
![1](https://f.cloud.github.com/assets/24104/1897071/5569e738-7bca-11e3-8a0c-790de7738f8d.PNG)

2) then after close and re-open Tiled:
![2](https://f.cloud.github.com/assets/24104/1897073/5a6a321a-7bca-11e3-813f-5112f95d5793.PNG)

my 2 cents: seems to be a problem only on default-right widgets, on left there is no problem O_O

**Comment by bjorn** [comment] 2016-07-10 10:46
This issue stalled a long time ago because I could not reproduce the problem. Tiled already remembers both the position and the size of these views. I'm still not sure what the problem could be here.

Could @Gornova and @CyberMew maybe try the current version of Tiled, to see if the problem has somehow been fixed in the meantime?

**Comment by CyberMew** [comment] 2016-07-10 15:26
Haven't been using Tiled for 2 years :o 

Just installed it and it seems fixed :dancer: 

Just a side note, I found an app named `Enfusoft` that could let you tiled patterns easily and quickly. Do you think Tiled will have some of the basic features as well? After all, this is `Tiled` :heart_eyes:

**Comment by Gornova** [comment] 2016-07-12 06:36
My test system is windows 8.1 64 bit

1) downloaded 0.16.2 for windows 32bit
2) downloaded this tileset for example http://opengameart.org/content/hearts-platformer-tileset-32-pixels
3) created a new map and resized tiled window

![before](https://cloud.githubusercontent.com/assets/24104/16757313/5f7c1ac4-480b-11e6-85b2-3a45293d7fa0.png)

4) closed and reopened the same map

![after](https://cloud.githubusercontent.com/assets/24104/16757321/6b71ea98-480b-11e6-86ba-2ddcdb1b1fdb.png)

For me this issue is not fixed! As you can see properties panel on left is not readable when I reopen tiled

**Comment by CyberMew** [comment] 2016-07-12 07:21
It worked for me on a windows 7 x64 machine, but I believe it was a brand new install and not an upgrade over existing installation. Not sure if that affects anything. And in my test I only tried to adjust the right panels and not the left panels. Maybe I'll try to test again when I am at home.

**Comment by CyberMew** [comment] 2016-07-12 16:02
Yup no issues for me. Forgot to mention that I am on the 64 bit Tiled setup. @Gornova is this a fresh install and/or a fresh project? Maybe you can try the 64 bit installer (to a new folder) with a fresh project and see how it goes?

**Comment by Gornova** [comment] 2016-07-12 16:52
same for 64bit version :(

**Comment by bjorn** [comment] 2016-07-17 11:59
This seems to have to do with maximizing the window. Due to the way this state is restored, the positions of the views are not correctly restored when the "normal" window state is not big enough, even if Tiled is actually maximized.

I wonder if there is some kind of workaround by code. For the user, a workaround is to make the window large before maximizing.

**Comment by bjorn** [comment] 2016-07-17 12:40
After some testing I believe this is an issue in Qt that I can't fix on the Tiled side.

Even if I explicitly restore the size of the window first, then restore the positions of the views (called `QMainWindow::restoreState`) and afterwards restore the full geometry (`QMainWindow::restoreGeometry`), the views do not get correctly restored. It is as if `restoreGeometry` triggers a resize to "normal size" and then re-applies the maximized state. Temporarily reducing the size of the window is then leading to layout updates that cause the view positions to change.

And if I don't use `restoreGeometry` but rather restore position, size and window state myself, then it loses the ability to store its "normal size", which seems to be only kept internally.

**Comment by bjorn** [comment] 2022-05-13 09:42
I've tried to find a nice workaround for this issue, but it needs to be tested before putting it in the release. Builds including this workaround should become available at https://github.com/mapeditor/tiled/actions/runs/2318670767 (though GA appears to be having some issues at the moment).

I've personally tested it on Linux with builds against Qt 5.15.2 and Qt 6.3, but it should also be tested on Windows and macOS.

**Closed** 2022-05-16 15:21 UTC
Labels: bug, qt issue

**Comment by Gornova** [comment] 2022-05-16 16:14
Hi, I'm not able to test it on Windows, where is the link to download the build ?

**Comment by bjorn** [comment] 2022-05-16 18:48
> Hi, I'm not able to test it on Windows, where is the link to download the build ?

Builds are now available at https://github.com/mapeditor/tiled/actions/runs/2332896230 (scroll down to "Artifacts"), but it has been tested on Windows by others now and I've also adjusted the patch for macOS. The fix will soon be available in Tiled 1.8.5. :-)
