### ISSUE TITLE
[Request] support `offset` for each image in tileset

### ISSUE THREAD

**Issue by finscn** [mapeditor/tiled#3121] opened 2021-08-24 10:03 UTC
In my game, there are many objects with different size and different anchor.
So I need the feature for setting different offset for them .

![image](https://user-images.githubusercontent.com/288367/130597978-3766ee93-6f09-4267-b75c-a5c65fe97c3d.png)
 

Could you have this plan ?

**Comment by eishiya** [comment] 2022-11-24 23:49
This is a duplicate of #871

**Comment by bjorn** [comment] 2022-11-26 20:54
There's also a PR in progress for this feature, which I aim to help finish for Tiled 1.10: #3488. :-)

**Closed by bjorn** 2022-11-26 20:54 UTC
