### ISSUE TITLE
Custom Property Datatype - "Selection" / "Enum"

### ISSUE THREAD

**Issue by BlaXun** [mapeditor/tiled#3243] opened 2022-01-18 09:53 UTC
To prevent unaccepted values I think it would be really nice if custom properties could support a datatype "Enumeration".
That way, when adding objects with the Scripting API, we could easily "protect" the user from adding unaccepted values by providing a list of values to choose from.

If this is not possible, I suggest adding a signal to be emitted when a objects custom_property value was changed. At least that way we could verify the value and show a hint to the user that the given value is not accepted

**Comment by bjorn** [comment] 2022-01-18 10:12
This sounds like a duplicate of #1211, which was recently implemented and will be available in Tiled 1.8. I'm still working on making the custom enum (and class) types available in the scripting API, but the rest of the feature is available in the [Tiled 1.8 beta](https://github.com/mapeditor/tiled/releases/tag/v1.7.90).

**Closed by bjorn** 2022-01-18 10:12 UTC
Labels: feature
