### ISSUE TITLE
request: search and replace

### ISSUE THREAD

**Issue by pixelartgirl** [mapeditor/tiled#3706] opened 2023-05-16 21:24 UTC
i would like to request a feature to search for tiles in the tilemap (by selecting a tile from the tileset)

- all found tiles should be highlighted
- you could choose a tile from the tileset to replace the found tiles with (or from any other tileset added to the tilemap)

don't close this, it's a good feature request and it's NOT in there

**Comment by pixelartgirl** [comment] 2023-05-16 21:25
Example of use: replace all grass by another, replace water by another, ...
very usefull feature

**Comment by bjorn** [comment] 2023-05-17 07:26
I agree it's a good feature request, but this is a duplicate of #3335.

**Closed by bjorn** 2023-05-17 07:26 UTC

**Comment by bjorn** [comment] 2023-05-17 07:28
Regarding rule-based search & replace, this feature already exists as [Automapping](https://doc.mapeditor.org/de/latest/manual/automapping/).
